### ISSUE TITLE
State relation to getAwesomeness()

### ISSUE THREAD

**Issue by koppor** [lockys/awesome.json#1]
[getAwesomeness()](https://github.com/panzhangwang/getAwesomeness) also provides a [json-based list](https://github.com/panzhangwang/getAwesomeness/blob/master/db.json). It would be fine, if the two formats were the same or that the difference was stated explicitly.

**Comment by lockys** [comment]
ah! Thanks for informing.
It's nice to see this. :100:

**Comment by koppor** [comment]
[The definitive list of lists (of lists) curated on GitHub](https://github.com/jnv/lists) offers its [data as CSV file](https://github.com/jnv/lists/blob/gh-pages/lists.csv). Maybe that is an inspiration, too?

**Comment by lockys** [comment]
Yes, I have seen that.
the `csv` of `jnv/list` is a good resource and up-to-date :)
We should make good use of it!
