### ISSUE TITLE
is there any API made by u for getting awesome 

### ISSUE THREAD

**Issue by pranavlathigara** [lockys/awesome.json#287]

**Comment by lockys** [comment]
Do you mean that a web service with the ability to provide awesome list in `JSON` format?
If yes, no for now.
But you can run this module to generate awesome list in `JSON` format, like
```sh
$ npm run awesome # To get the latest awesome list.
$ npm run build # To get whole links under every awesome.
```
Thanks.

**Comment by pranavlathigara** [comment]
yes , web service....
